### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by Csino** [canonical/lxd-ui#1004]
# Description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Metadata

UI Version: 0.8.4
Path: /ui/project/Moba/instance/mongodb/configuration/network-devices

# Stacktrace

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at $1 (https://192.168.2.147:8443/ui/assets/index-fc04eb4e.js:40:26089)
    at pr (https://192.168.2.147:8443/ui/assets/index-fc04eb4e.js:40:27379)
    at N1 (https://192.168.2.147:8443/ui/assets/index-fc04eb4e.js:40:27839)
    at pr (https://192.168.2.147:8443/ui/assets/index-fc04eb4e.js:40:27529)
    at N1 (https://192.168.2.147:8443/ui/assets/index-fc04eb4e.js:40:27642)
    at pr (https://192.168.2.147:8443/ui/assets/index-fc04eb4e.js:40:27529)
    at N1 (https://192.168.2.147:8443/ui/assets/index-fc04eb4e.js:40:30579)
    at pr (https://192.168.2.147:8443/ui/assets/index-fc04eb4e.js:40:27529)
    at N1 (https://192.168.2.147:8443/ui/assets/index-fc04eb4e.js:40:27839)
    at pr (https://192.168.2.147:8443/ui/assets/index-fc04eb4e.js:40:27529)
```

**Comment by edlerd** [comment]
Thank you for the report. The URL from the report suggests, that you were in an instance network configuration. Can you please describe what interaction was leading to the error? Did you try to add or remove a network device right before?

**Comment by edlerd** [comment]
Are you using google chrome with automatic translation?

I can reproduce this, when enabling translation in chrome. Then removing a network interface from an instance leads to the above stack trace with the current 5.21 LTS version, that ships with UI version 0.8.4.

**Comment by edlerd** [comment]
Relevant [react issue](https://github.com/facebook/react/issues/11538) an open [chrome bug](https://issues.chromium.org/issues/41407169?pli=1) on this.
