### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by mzbgf** [canonical/lxd-ui#753]
```
TypeError: va[m] is not iterable (cannot read property undefined)
    at https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/CreateInstance-17c2d93e.js:1:2734
    at Array.map (<anonymous>)
    at _a (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/CreateInstance-17c2d93e.js:1:2678)
    at ja (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/CreateInstance-17c2d93e.js:1:3934)
    at Zg (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:38:19529)
    at B1 (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:40:44027)
    at L1 (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:40:39763)
    at m$ (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:40:39691)
    at Cd (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:40:39545)
    at Ym (https://3shudh9okimmhkhk3.neiwangyun.net:42540/ui/assets/index-b3f3eaed.js:40:35913)
```

**Comment by edlerd** [comment]
Thank you for reporting this, there was an issue with resolving the image architecture for s390x
