### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by vitepython** [canonical/lxd-ui#786]
```
Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zg (https://192.168.0.200:8443/ui/assets/index-b3f3eaed.js:38:19733)
    at Am (https://192.168.0.200:8443/ui/assets/index-b3f3eaed.js:40:3139)
    at B1 (https://192.168.0.200:8443/ui/assets/index-b3f3eaed.js:40:44801)
    at L1 (https://192.168.0.200:8443/ui/assets/index-b3f3eaed.js:40:39763)
    at m$ (https://192.168.0.200:8443/ui/assets/index-b3f3eaed.js:40:39691)
    at Cd (https://192.168.0.200:8443/ui/assets/index-b3f3eaed.js:40:39545)
    at Ym (https://192.168.0.200:8443/ui/assets/index-b3f3eaed.js:40:35913)
    at F0 (https://192.168.0.200:8443/ui/assets/index-b3f3eaed.js:40:36716)
    at hi (https://192.168.0.200:8443/ui/assets/index-b3f3eaed.js:38:3274)
    at eo (https://192.168.0.200:8443/ui/assets/index-b3f3eaed.js:40:37163)
```

**Comment by edlerd** [comment]
Thank you for reaching out.

I think this has been fixed with [this commit](https://github.com/canonical/lxd-ui/commit/1647a00df3b305d9910d103fee7e232c5ede501b#diff-850090c4ab0bb8a6f5c662830bea10666c074a1f0af2a5a62698c954a3aae848R66), which is currently pending a patch release for LXD 5.21 with UI version 0.8.1.
