### ISSUE TITLE
Error report on CephFS volume creation from UI 

### ISSUE THREAD

**Issue by khoubeibba** [canonical/lxd-ui#996]
# Description

Using LXD-UI  : Error when trying to create a volume using cephfs driver  
Using the CLI  : OK 

# Metadata
microcloud cluster 2.1.0 LTS
lxd 5.21.2 LTS
ceph-version: 19.2.0-0ubuntu0.24.04.1; microceph-git: 9aeaeb2970
openvswitch: 3.3.0-1ubuntu3
UI Version: 0.8.4
Path: /ui/project/default/storage

# Stacktrace

```
Error: Could not find cephfs in storagePoolDriverToOptionKey
    at O (https://10.52.2.142:8443/ui/assets/FormMenuItem-42448b7e.js:1:4491)
    at ie (https://10.52.2.142:8443/ui/assets/FormMenuItem-42448b7e.js:1:5816)
    at se (https://10.52.2.142:8443/ui/assets/FormMenuItem-42448b7e.js:1:4920)
    at je (https://10.52.2.142:8443/ui/assets/FormMenuItem-42448b7e.js:1:8168)
    at ee (https://10.52.2.142:8443/ui/assets/StorageVolumeForm-b05fb09e.js:1:4772)
    at Zg (https://10.52.2.142:8443/ui/assets/index-fc04eb4e.js:38:19529)
    at Am (https://10.52.2.142:8443/ui/assets/index-fc04eb4e.js:40:3139)
    at B1 (https://10.52.2.142:8443/ui/assets/index-fc04eb4e.js:40:44801)
    at L1 (https://10.52.2.142:8443/ui/assets/index-fc04eb4e.js:40:39763)
    at v$ (https://10.52.2.142:8443/ui/assets/index-fc04eb4e.js:40:39691)
```

**Comment by khoubeibba** [comment]
Thank you for your return
Here's a video 
[screen-capture.webm](https://github.com/user-attachments/assets/07d58668-ae61-41ea-aa25-9558394c6319)

**Comment by khoubeibba** [comment]
Thanks @edlerd  for the info, but what I don't understand is the fact that I was able to create a volume on the remote-fs storage pool and I can see it on the UI 
`lxc storage volume create remote-fs another-volume` 
![image](https://github.com/user-attachments/assets/cc208ac8-ff9a-41ce-b575-af2effad2df3)

**Comment by edlerd** [comment]
Thanks for your message, you are right. According to the [docs on cephfs](https://localhost:8443/documentation/reference/storage_cephfs/#cephfs-driver-in-lxd) volumes can be created, but only with type filesystem. In that case, I'll change the fix accordingly.
